---
version: '3.7'

services:
  app:
    image: pixelfed
    restart: unless-stopped
    # Traefik configuration
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.pixel.rule=Host(`pixelfed.example.com`)"
      - "traefik.http.routers.pixel.entrypoints=https"
      - "traefik.http.routers.pixel.tls.certresolver=example"
    # If you don't want Traefik, but have your own reverse proxy, expose the port
    # ports:
    #   - "127.0.0.1:8080:80"
    env_file:
      - ./.env
    volumes:
      - "app-storage:/var/www/storage"
      - "app-bootstrap:/var/www/bootstrap"
    networks:
      - traefik
      - internal

  worker:
    image: pixelfed
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - "app-storage:/var/www/storage"
      - "app-bootstrap:/var/www/bootstrap"
    networks:
      - traefik
      - internal
    command: gosu www-data php artisan horizon
    
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - internal
    environment:
      - MYSQL_DATABASE=pixelfed
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - "db-data:/var/lib/mysql"

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=640
    volumes:
      - "redis-data:/data"
    networks:
      - internal

volumes:
  redis-data:
  db-data:
  app-storage:
  app-bootstrap:  

networks:
  traefik:
    external:
      name: traefik
  internal:
    internal: true
