[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

[log]
  level = "INFO"

[api]
  insecure = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedbydefault=false

[certificatesresolvers.example.acme]
  email = "info@example.com"
  storage = "/letsencrypt/acme.json"

  [certificatesresolvers.example.acme.dnsChallenge]
    provider = "route53"
    delayBeforeCheck = 0
